# render.yaml
databases:
  - name: wasichana-db
    region: oregon
    plan: free
    databaseName: wasichana
    user: msichana_user

services:
  # 1) Flask API
  - type: web
    name: wasichana-api
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      pip install --upgrade pip
      pip install gunicorn
      pip install -r backend/requirements.txt
      export FLASK_APP=backend/app.py
      flask --app backend/app.py db upgrade
      python backend/seed.py
    startCommand: |
      gunicorn --chdir backend --bind 0.0.0.0:$PORT --workers=1 --threads=4 app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wasichana-db
          property: connectionString
      - key: JWT_SECRET_KEY
        value: dreamflasdc3septeebb2b3eadc3ed4f8ec6c9fb3b7a57ed5fb51b327853bc5
      - key: FLASK_ENV
        value: production
      - key: UPLOAD_FOLDER
        value: ./uploads

  # 2) React frontend
  - type: web
    name: wasichana-ui
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      cd client
      npm install
      npm run build
    startCommand: |
      cd client
      npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: VITE_API_BASE_URL
        # replace with your actual Render service URL after it's created:
        value: https://wasichana-api.onrender.com
