databases:
  - name: wasichana-db
    region: oregon
    plan: free
    databaseName: wasichana
    user: dbadmin

services:
  - type: web
    name: Tuinue-Wasichana-API
    env: python
    region: oregon
    plan: free
    branch: main
    rootDir: .
    buildCommand: |
      pip install --upgrade pip
      pip install python-dotenv gunicorn
      pip install -r requirements.txt

      echo "Contents of routes.py:"
      cat backend/routes/routes.py
      
      # Set Flask app environment variable
      export FLASK_APP=backend.config:create_app
      
      # Initialize database (skip if already exists)
      [ ! -d "migrations" ] && flask db init || true
      
      # Generate and run migrations (skip if no changes)
      flask db migrate -m "initial migration" || true
      flask db upgrade
      
      # Create tables if migrations fail (safety net)
      PYTHONPATH=/opt/render/project/src python -c "
      from backend.config import create_app
      app = create_app()
      with app.app_context():
          from backend.models import db
          try:
              db.create_all()
          except Exception as e:
              print(f'Database tables already exist: {str(e)}')
      "
      
      # Conditional seeding
      PYTHONPATH=/opt/render/project/src python -c "
      from backend.config import create_app
      from backend.models import Donation
      app = create_app()
      with app.app_context():
          if Donation.query.count() == 0:
              from backend.seed import seed_database
              seed_database()
              print('Database seeded successfully')
          else:
              print('Database already contains data - skipping seeding')
      "

    startCommand: |
      gunicorn --bind 0.0.0.0:$PORT 'backend.config:create_app()'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wasichana-db
          property: connectionString
      - key: FLASK_SECRET_KEY
        value: 460afb43de33e919e8b02b35ed4c3e4465ec8c0fb3b7a5fe15f861b3278515c5
      - key: JWT_SECRET_KEY
        value: 392832fc3fe988535d689bcdb93c49581983f7d2ae0881238a269ceb4d18fe84
      - key: FLASK_ENV
        value: production
      - key: UPLOAD_FOLDER
        value: ./uploads
      - key: FLASK_APP
        value: backend.config:create_app

  - type: web
    name: Tuinue-Wasichana-UI
    env: node
    region: oregon
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: |
      echo "20" > .nvmrc
      npm install
      npm run build
    startCommand: |
      npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: CORS_ALLOWED_ORIGINS
        value: "http://localhost:5173,https://tuinue-wasichana-ui-dw85.onrender.com"