"""Make donation fields non-nullable

Revision ID: 019b06cdd33b
Revises: 26e8058203a3
Create Date: 2025-07-24 23:12:42.208353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019b06cdd33b'
down_revision = '26e8058203a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
