"""Add beneficiary_id to Story

Revision ID: 04e67012700e
Revises: 5a2085c7266c
Create Date: 2025-07-24 15:50:02.401316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e67012700e'
down_revision = '5a2085c7266c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beneficiary_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'beneficiaries', ['beneficiary_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('beneficiary_id')

    # ### end Alembic commands ###
