"""Add beneficiary_id to Inventory

Revision ID: 07ef6d0a423a
Revises: 04e67012700e
Create Date: 2025-07-24 15:51:28.913432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ef6d0a423a'
down_revision = '04e67012700e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('beneficiary_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('inventory_donor_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('inventory_charity_id_fkey', type_='foreignkey')
        batch_op.drop_column('item')
        batch_op.drop_column('charity_id')
        batch_op.drop_column('donor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donor_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('charity_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('item', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('inventory_charity_id_fkey', 'charities', ['charity_id'], ['id'])
        batch_op.create_foreign_key('inventory_donor_id_fkey', 'donors', ['donor_id'], ['id'])
        batch_op.alter_column('beneficiary_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('quantity')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
