"""Add is_anonymous field to Donor

Revision ID: 0da8ccdbe2ce
Revises: e217e6a2f719
Create Date: 2025-07-24 22:49:55.514673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da8ccdbe2ce'
down_revision = 'e217e6a2f719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_column('is_anonymous')

    # ### end Alembic commands ###
