"""Add status to Charity

Revision ID: 0f4ce2d2772a
Revises: 26684d1a54e0
Create Date: 2025-07-24 17:05:52.363912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4ce2d2772a'
down_revision = '26684d1a54e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))
        batch_op.alter_column('mission',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('email')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.alter_column('mission',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
