"""Add email to charity

Revision ID: 34c0c1ef6d75
Revises: 0f4ce2d2772a
Create Date: 2025-07-24 17:15:33.190314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c0c1ef6d75'
down_revision = '0f4ce2d2772a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
