"""adds foreignkey to beneficiary.py

Revision ID: 6be77e88f435
Revises: fbc6564be09a
Create Date: 2025-07-28 06:57:23.596708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be77e88f435'
down_revision = 'fbc6564be09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.drop_constraint('beneficiaries_donor_id_fkey', type_='foreignkey')
        batch_op.drop_column('donor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donor_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('beneficiaries_donor_id_fkey', 'donors', ['donor_id'], ['id'])

    # ### end Alembic commands ###
