"""Adds missing columns to tables

Revision ID: e217e6a2f719
Revises: 4b6f44d4ff79
Create Date: 2025-07-24 19:41:38.680950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e217e6a2f719'
down_revision = '4b6f44d4ff79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donor_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('message', sa.String(), nullable=True))

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_column('message')
        batch_op.drop_column('donor_name')

    # ### end Alembic commands ###
