"""updated models

Revision ID: f99a58ac83ea
Revises: 3b1dfcb9e125
Create Date: 2025-07-18 23:59:41.165756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f99a58ac83ea'
down_revision = '3b1dfcb9e125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beneficiary')
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('email')

    op.create_table('beneficiary',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('charity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('school', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('supplies_received', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], name='beneficiary_charity_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='beneficiary_pkey')
    )
    # ### end Alembic commands ###
